### PR TITLE
Fix of "Invalid style number causes Excel 2016 warning" #365 

### PR DESCRIPTION
**Pull request by melehin**
A file created by NewStreamFileBuilder opens without recovery messages (in my case via MS One Drive) after this fix.
And this test case works well (without **panic: runtime error: index out of range**)
```
package main

import (
    "bytes"

    "github.com/tealeg/xlsx"
)

func main() {
    buf := &bytes.Buffer{}
    f := xlsx.NewStreamFileBuilder(buf)
    ctype := xlsx.CellTypeString
    if err := f.AddSheet(
        "messages",
        []string{"foo", "bar"},
        []*xlsx.CellType{&ctype, &ctype},
    ); err != nil {
        panic(err)
    }

    stream, err := f.Build()
    if err != nil {
        panic(err)
    }
    stream.WriteAll([][]string{
        {"row1a", "row1b"},
    })
    stream.Close()

    if _, err = xlsx.OpenBinary(buf.Bytes()); err != nil {
        panic(err)
    }
}
```

_Originally posted by @alicebob in https://github.com/tealeg/xlsx/issues/365#issuecomment-506320321_

### CODE REVIEW

**Comment by alicebob** [comment]
Great, thanks!

**Comment by alicebob** [comment]
I just tried this branch to generate a document with a few columns and 500K rows, worked great in google docs. Thanks, @melehin!

**Comment by alicebob** [comment]
Hi @ryho, sorry to bother you directly, but this PR fixes the issue I have with producing streaming output. Is there anything you need before you can merge it?

**Comment by zkanda** [comment]
Ping @ryho, would be good if we can merge this.

**Pull request closed without merging**
