### PR TITLE
Read struct from row based on xlsx tags.

### PR DESCRIPTION
**Pull request by thewraven**
Supported types: bool,int{8,16,32,64},float64,string, time.Time

Also custom deserialization is supported via XSLXUnmarshaler interface

### CODE REVIEW

**Comment by thewraven** [comment]
This is an implementation for issue #305

**Comment by tealeg** [comment]
Hi @thewraven this is looking interesting.  Can you address the failing test above?

**Comment by thewraven** [comment]
Sure, I'll submit the change when its ready :+1:

**Comment by tealeg** [comment]
@thewraven great work.  I'll merge this is as is.  I might eventually create an "examples" directory and move your example code in there.

**Pull request merged**
