### PR TITLE
[bug report] index of range in a xlxs with blank line in wps

### PR DESCRIPTION
**Pull request by bronze1man**
It all works fine in commit eea16ed5b60c88c33c25204cf93c6c3f8726ec82
It not work in master branch
I add a test xlxs file in this pr.

```
$ go test
panic: runtime error: index out of range

goroutine 48 [running]:
runtime.panic(0x5131a0, 0x69a7b7)
        C:/home/go/src/pkg/runtime/panic.c:266 +0xa6
_/C_/xxxx/src/github.com/tealeg/xlsx.readRowsFromSheet(0x125ef0a0, 0x125f0360, 0x1260b5f0, 0x1, 0x1260b600, ...)
        C:/xxxx/src/github.com/tealeg/xlsx/lib.go:325 +0x3ad
_/C_/xxxx/src/github.com/tealeg/xlsx.readSheetFromFile(0x125f2b00, 0x0, 0x1260b5e0, 0x6, 0x1260b5f0, ...)
        C:/xxxx/src/github.com/tealeg/xlsx/lib.go:364 +0xd1
created by _/C_/xxxx/src/github.com/tealeg/xlsx.readSheetsFromZipFile
        C:/xxxx/src/github.com/tealeg/xlsx/lib.go:393 +0x28e

goroutine 1 [chan receive]:
testing.RunTests(0x56a9a8, 0x699760, 0x1b, 0x1b, 0x1)
        C:/home/go/src/pkg/testing/testing.go:472 +0x6ed
testing.Main(0x56a9a8, 0x699760, 0x1b, 0x1b, 0x69cc60, ...)
        C:/home/go/src/pkg/testing/testing.go:403 +0x6a
main.main()
        _/C_/xxxx/src/github.com/tealeg/xlsx/_test/_testmain.go:99 +0x82

goroutine 47 [chan receive]:
_/C_/xxxx/src/github.com/tealeg/xlsx.readSheetsFromZipFile(0x125f3ba0, 0x125f0360, 0x125d6680, 0x0, 0x0, ...)
        C:/xxxx/src/github.com/tealeg/xlsx/lib.go:396 +0x2cf
_/C_/xxxx/src/github.com/tealeg/xlsx.ReadZip(0x125fcf00, 0x15, 0x125fcf00, 0x0)
        C:/xxxx/src/github.com/tealeg/xlsx/lib.go:550 +0x2cf
_/C_/xxxx/src/github.com/tealeg/xlsx.OpenFile(0x543588, 0x15, 0x3237827c, 0x134b4f12, 0x3b9aca00)
        C:/xxxx/src/github.com/tealeg/xlsx/lib.go:488 +0x5f
_/C_/xxxx/src/github.com/tealeg/xlsx.TestWpsBlankLine(0x125f37e0)
        C:/xxxx/src/github.com/tealeg/xlsx/wpsBlankLine_test.go:10 +0x2f
testing.tRunner(0x125f37e0, 0x699898)
        C:/home/go/src/pkg/testing/testing.go:391 +0x87
created by testing.RunTests
        C:/home/go/src/pkg/testing/testing.go:471 +0x6d2
exit status 2
FAIL    _/C_/xxxx/src/github.com/tealeg/xlsx       0.109s
```

### CODE REVIEW

**Comment by natdm** [comment]
Getting the same error in one of my docs.

Code here: https://github.com/natdm/japan_price_schedule/blob/master/priceschedule.go

Only happens when end of file has blank lines..

**Comment by tealeg** [comment]
@natdm can you confirm that you still encounter this issue with the current code?

**Comment by natdm** [comment]
Was there a commit to fix this? Which one?

**Comment by tealeg** [comment]
@natdm I'm actually just looking for confirmation that this issue is different from the one we already having a passing test case for.  The original issue was fixed by this merge : 

https://github.com/tealeg/xlsx/commit/1c39a700aec21c9f12ae4aaa7ac4a539c53aa394

**Pull request merged**
