### PR TITLE
Can output times and dates with custom formats and timezones.

### PR DESCRIPTION
**Pull request by ds0nt**
https://github.com/tealeg/xlsx/issues/273

### CODE REVIEW

**Comment by tealeg** [comment]
Sorry for the late review.  There should be unit tests to cover this new functionality, otherwise we can't be sure that we don't regress following future changes.  Any chance you could add some?

**Comment by ds0nt** [comment]
I'll try and give it a look this weekend, depending on life-stuff.

Thanks!

**Comment by ds0nt** [comment]
I've updated the tests. Can you take a look and see if you think they reasonably test all cases? I think there could be some corner-cases I am missing, but here's an attempt.

**Comment by tealeg** [comment]
@ds0nt sorry for the delay here.  I've been distracted looking for a job!  Anyhow, this looks good now, I'm just resolving a conflict for you and rerunning the tests.  Should land shortly.

**Pull request merged**
