### PR TITLE
support hyperlink

### PR DESCRIPTION
**Pull request by extrame**
read hyperlink to each cell

### CODE REVIEW

**Comment by ShawnMilo** [comment]
Hi, @extrame. I'd like to help get this change merged. It has fallen out of date and hasn't been discussed in a while. If you have time to add the tests and update it from the latest version of `master` I'll look at it. Thanks.

**Comment by extrame** [comment]
Sorry, I forgot...
Let me do this in weekend

On Wed, May 13, 2015 at 9:56 PM, Shawn Milochik <notifications@github.com>
wrote:

> Hi, @extrame <https://github.com/extrame>. I'd like to help get this
> change merged. It has fallen out of date and hasn't been discussed in a
> while. If you have time to add the tests and update it from the latest
> version of master I'll look at it. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tealeg/xlsx/pull/64#issuecomment-101671004>.
>



-- 
Liu Ming

**Comment by yhbyun** [comment]
I am developing a go program that read data from database and save it to a excel file.

I want to add a cell with hyperlink, but I can't figure it out how to do with `xlsx` package.

`xlsx` package is supporting this feature?

**Comment by tealeg** [comment]
@yhbyun there's not facility to do that right now, but I suspect it wouldn't be a hard thing to add.

**Comment by ShawnMilo** [comment]
@yhbyun @tealeg: Isn't this conversation taking place in a pull request for that very feature? Maybe it'll be coming in the near future. hoping

**Comment by tealeg** [comment]
Sadly this pull request is looking quite rotted at this point - I had a look at it last night, but the conflicts overwhelm the core meaning of the branch (which is actually quite simple I believe).    I'm going to close the pull request, but feel free to submit a new one if you wish.

**Pull request closed without merging**
