### PR TITLE
Incorrect parsed date fix

### LINKED ISSUE #229: Incorrect parsed date in some cases
# Used code to test:

```golang
package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/tealeg/xlsx"
)

func main() {
	f, err := xlsx.OpenFile("test.xlsx")
	if err != nil {
		log.Fatal(err)
	}
	sheet := f.Sheets[0]
	for _, row := range sheet.Rows {
		cells := row.Cells

		got, err := cells[0].String()
		if err != nil {
			log.Fatal(err)
		}

		expected, err := cells[1].String()
		if err != nil {
			log.Fatal(err)
		}
		expected = strings.Replace(expected, "-", ":", 1)
		if got != expected {
			fmt.Printf("expected %s; got %s\n", expected, got)
		}
	}
}
```

# Used spreadsheet **(third column is the "parsed" value by the library)**:
[test.xlsx](https://github.com/tealeg/xlsx/files/319319/test.xlsx)

# Description
In some time values, the time is being parsed incorrectly. I made a table with all possible values (00:00  to 23:59) and here is the output:

# Output
```bash
expected 00:03; got 01:01
expected 00:04; got 01:02
expected 00:07; got 01:05
expected 00:08; got 01:06
expected 00:11; got 01:09
expected 00:12; got 01:10
expected 00:15; got 01:13
expected 00:16; got 01:14
expected 00:19; got 01:17
expected 00:20; got 01:18
expected 00:23; got 01:21
expected 00:24; got 01:22
expected 00:27; got 01:25
expected 00:28; got 01:26
expected 00:31; got 01:29
expected 00:32; got 01:30
expected 00:35; got 01:33
expected 00:36; got 01:34
expected 00:39; got 01:37
expected 00:40; got 01:38
expected 00:43; got 01:41
expected 00:44; got 01:42
expected 00:48; got 01:46
expected 00:49; got 01:47
expected 00:52; got 01:50
expected 00:53; got 01:51
expected 00:56; got 01:54
expected 00:57; got 01:55
expected 01:00; got 01:58
expected 01:01; got 01:59
expected 01:04; got 02:02
expected 01:05; got 02:03
expected 01:08; got 02:06
expected 01:09; got 02:07
expected 01:12; got 02:10
expected 01:13; got 02:11
expected 01:16; got 02:14
expected 01:17; got 02:15
expected 01:20; got 02:18
expected 01:21; got 02:19
expected 01:24; got 02:22
expected 01:25; got 02:23
expected 01:28; got 02:26
expected 01:29; got 02:27
expected 01:33; got 02:31
expected 01:34; got 02:32
expected 01:37; got 02:35
expected 01:38; got 02:36
expected 01:41; got 02:39
expected 01:42; got 02:40
expected 01:45; got 02:43
expected 01:46; got 02:44
expected 01:49; got 02:47
expected 01:50; got 02:48
expected 01:53; got 02:51
expected 01:54; got 02:52
expected 01:57; got 02:55
expected 01:58; got 02:56
expected 02:01; got 02:59
expected 02:02; got 03:00
expected 02:05; got 03:03
expected 02:06; got 03:04
expected 02:09; got 03:07
expected 02:10; got 03:08
expected 02:13; got 03:11
expected 02:14; got 03:12
expected 02:18; got 03:16
expected 02:19; got 03:17
expected 02:22; got 03:20
expected 02:23; got 03:21
expected 02:26; got 03:24
expected 02:27; got 03:25
expected 02:30; got 03:28
expected 02:31; got 03:29
expected 02:34; got 03:32
expected 02:35; got 03:33
expected 02:38; got 03:36
expected 02:39; got 03:37
expected 02:42; got 03:40
expected 02:43; got 03:41
expected 02:46; got 03:44
expected 02:47; got 03:45
expected 02:50; got 03:48
expected 02:51; got 03:49
expected 02:54; got 03:52
expected 02:55; got 03:53
expected 02:58; got 03:56
expected 02:59; got 03:57
expected 03:03; got 04:01
expected 03:04; got 04:02
expected 03:07; got 04:05
expected 03:08; got 04:06
expected 03:11; got 04:09
expected 03:12; got 04:10
expected 03:15; got 04:13
expected 03:16; got 04:14
expected 03:19; got 04:17
expected 03:20; got 04:18
expected 03:23; got 04:21
expected 03:24; got 04:22
expected 03:27; got 04:25
expected 03:28; got 04:26
expected 03:31; got 04:29
expected 03:32; got 04:30
expected 03:35; got 04:33
expected 03:36; got 04:34
expected 03:39; got 04:37
expected 03:40; got 04:38
expected 03:43; got 04:41
expected 03:44; got 04:42
expected 03:48; got 04:46
expected 03:49; got 04:47
expected 03:52; got 04:50
expected 03:53; got 04:51
expected 03:56; got 04:54
expected 03:57; got 04:55
expected 04:00; got 04:58
expected 04:01; got 04:59
expected 04:04; got 05:02
expected 04:05; got 05:03
expected 04:08; got 05:06
expected 04:09; got 05:07
expected 04:12; got 05:10
expected 04:13; got 05:11
expected 04:16; got 05:14
expected 04:17; got 05:15
expected 04:20; got 05:18
expected 04:21; got 05:19
expected 04:24; got 05:22
expected 04:25; got 05:23
expected 04:28; got 05:26
expected 04:29; got 05:27
expected 04:33; got 05:31
expected 04:34; got 05:32
expected 04:37; got 05:35
expected 04:38; got 05:36
expected 04:41; got 05:39
expected 04:42; got 05:40
expected 04:45; got 05:43
expected 04:46; got 05:44
expected 04:49; got 05:47
expected 04:50; got 05:48
expected 04:53; got 05:51
expected 04:54; got 05:52
expected 04:57; got 05:55
expected 04:58; got 05:56
expected 05:01; got 05:59
expected 05:02; got 06:00
expected 05:05; got 06:03
expected 05:06; got 06:04
expected 05:09; got 06:07
expected 05:10; got 06:08
expected 05:13; got 06:11
expected 05:14; got 06:12
expected 05:18; got 06:16
expected 05:19; got 06:17
expected 05:22; got 06:20
expected 05:23; got 06:21
expected 05:26; got 06:24
expected 05:27; got 06:25
expected 05:30; got 06:28
expected 05:31; got 06:29
expected 05:34; got 06:32
expected 05:35; got 06:33
expected 05:38; got 06:36
expected 05:39; got 06:37
expected 05:42; got 06:40
expected 05:43; got 06:41
expected 05:46; got 06:44
expected 05:47; got 06:45
expected 05:50; got 06:48
expected 05:51; got 06:49
expected 05:54; got 06:52
expected 05:55; got 06:53
expected 05:58; got 06:56
expected 05:59; got 06:57
expected 06:03; got 07:01
expected 06:04; got 07:02
expected 06:07; got 07:05
expected 06:08; got 07:06
expected 06:11; got 07:09
expected 06:12; got 07:10
expected 06:15; got 07:13
expected 06:16; got 07:14
expected 06:19; got 07:17
expected 06:20; got 07:18
expected 06:23; got 07:21
expected 06:24; got 07:22
expected 06:27; got 07:25
expected 06:28; got 07:26
expected 06:31; got 07:29
expected 06:32; got 07:30
expected 06:35; got 07:33
expected 06:36; got 07:34
expected 06:39; got 07:37
expected 06:40; got 07:38
expected 06:43; got 07:41
expected 06:44; got 07:42
expected 06:48; got 07:46
expected 06:49; got 07:47
expected 06:52; got 07:50
expected 06:53; got 07:51
expected 06:56; got 07:54
expected 06:57; got 07:55
expected 07:00; got 07:58
expected 07:01; got 07:59
expected 07:04; got 08:02
expected 07:05; got 08:03
expected 07:08; got 08:06
expected 07:09; got 08:07
expected 07:12; got 08:10
expected 07:13; got 08:11
expected 07:16; got 08:14
expected 07:17; got 08:15
expected 07:20; got 08:18
expected 07:21; got 08:19
expected 07:24; got 08:22
expected 07:25; got 08:23
expected 07:28; got 08:26
expected 07:29; got 08:27
expected 07:33; got 08:31
expected 07:34; got 08:32
expected 07:37; got 08:35
expected 07:38; got 08:36
expected 07:41; got 08:39
expected 07:42; got 08:40
expected 07:45; got 08:43
expected 07:46; got 08:44
expected 07:49; got 08:47
expected 07:50; got 08:48
expected 07:53; got 08:51
expected 07:54; got 08:52
expected 07:57; got 08:55
expected 07:58; got 08:56
expected 08:01; got 08:59
expected 08:02; got 09:00
expected 08:05; got 09:03
expected 08:06; got 09:04
expected 08:09; got 09:07
expected 08:10; got 09:08
expected 08:13; got 09:11
expected 08:14; got 09:12
expected 08:18; got 09:16
expected 08:19; got 09:17
expected 08:22; got 09:20
expected 08:23; got 09:21
expected 08:26; got 09:24
expected 08:27; got 09:25
expected 08:30; got 09:28
expected 08:31; got 09:29
expected 08:34; got 09:32
expected 08:35; got 09:33
expected 08:38; got 09:36
expected 08:39; got 09:37
expected 08:42; got 09:40
expected 08:43; got 09:41
expected 08:46; got 09:44
expected 08:47; got 09:45
expected 08:50; got 09:48
expected 08:51; got 09:49
expected 08:54; got 09:52
expected 08:55; got 09:53
expected 08:58; got 09:56
expected 08:59; got 09:57
expected 09:03; got 10:01
expected 09:04; got 10:02
expected 09:07; got 10:05
expected 09:08; got 10:06
expected 09:11; got 10:09
expected 09:12; got 10:10
expected 09:15; got 10:13
expected 09:16; got 10:14
expected 09:19; got 10:17
expected 09:20; got 10:18
expected 09:23; got 10:21
expected 09:24; got 10:22
expected 09:27; got 10:25
expected 09:28; got 10:26
expected 09:31; got 10:29
expected 09:32; got 10:30
expected 09:35; got 10:33
expected 09:36; got 10:34
expected 09:39; got 10:37
expected 09:40; got 10:38
expected 09:43; got 10:41
expected 09:44; got 10:42
expected 09:48; got 10:46
expected 09:49; got 10:47
expected 09:52; got 10:50
expected 09:53; got 10:51
expected 09:56; got 10:54
expected 09:57; got 10:55
expected 10:00; got 10:58
expected 10:01; got 10:59
expected 10:04; got 11:02
expected 10:05; got 11:03
expected 10:08; got 11:06
expected 10:09; got 11:07
expected 10:12; got 11:10
expected 10:13; got 11:11
expected 10:16; got 11:14
expected 10:17; got 11:15
expected 10:20; got 11:18
expected 10:21; got 11:19
expected 10:24; got 11:22
expected 10:25; got 11:23
expected 10:28; got 11:26
expected 10:29; got 11:27
expected 10:33; got 11:31
expected 10:34; got 11:32
expected 10:37; got 11:35
expected 10:38; got 11:36
expected 10:41; got 11:39
expected 10:42; got 11:40
expected 10:45; got 11:43
expected 10:46; got 11:44
expected 10:49; got 11:47
expected 10:50; got 11:48
expected 10:53; got 11:51
expected 10:54; got 11:52
expected 10:57; got 11:55
expected 10:58; got 11:56
expected 11:01; got 11:59
expected 11:02; got 12:00
expected 11:05; got 12:03
expected 11:06; got 12:04
expected 11:09; got 12:07
expected 11:10; got 12:08
expected 11:13; got 12:11
expected 11:14; got 12:12
expected 11:18; got 12:16
expected 11:19; got 12:17
expected 11:22; got 12:20
expected 11:23; got 12:21
expected 11:26; got 12:24
expected 11:27; got 12:25
expected 11:30; got 12:28
expected 11:31; got 12:29
expected 11:34; got 12:32
expected 11:35; got 12:33
expected 11:38; got 12:36
expected 11:39; got 12:37
expected 11:42; got 12:40
expected 11:43; got 12:41
expected 11:46; got 12:44
expected 11:47; got 12:45
expected 11:50; got 12:48
expected 11:51; got 12:49
expected 11:54; got 12:52
expected 11:55; got 12:53
expected 11:58; got 12:56
expected 11:59; got 12:57
expected 12:03; got 13:01
expected 12:04; got 13:02
expected 12:07; got 13:05
expected 12:08; got 13:06
expected 12:11; got 13:09
expected 12:12; got 13:10
expected 12:15; got 13:13
expected 12:16; got 13:14
expected 12:19; got 13:17
expected 12:20; got 13:18
expected 12:23; got 13:21
expected 12:24; got 13:22
expected 12:27; got 13:25
expected 12:28; got 13:26
expected 12:31; got 13:29
expected 12:32; got 13:30
expected 12:35; got 13:33
expected 12:36; got 13:34
expected 12:39; got 13:37
expected 12:40; got 13:38
expected 12:43; got 13:41
expected 12:44; got 13:42
expected 12:48; got 13:46
expected 12:49; got 13:47
expected 12:52; got 13:50
expected 12:53; got 13:51
expected 12:56; got 13:54
expected 12:57; got 13:55
expected 13:00; got 13:58
expected 13:01; got 13:59
expected 13:04; got 14:02
expected 13:05; got 14:03
expected 13:08; got 14:06
expected 13:09; got 14:07
expected 13:12; got 14:10
expected 13:13; got 14:11
expected 13:16; got 14:14
expected 13:17; got 14:15
expected 13:20; got 14:18
expected 13:21; got 14:19
expected 13:24; got 14:22
expected 13:25; got 14:23
expected 13:28; got 14:26
expected 13:29; got 14:27
expected 13:33; got 14:31
expected 13:34; got 14:32
expected 13:37; got 14:35
expected 13:38; got 14:36
expected 13:41; got 14:39
expected 13:42; got 14:40
expected 13:45; got 14:43
expected 13:46; got 14:44
expected 13:49; got 14:47
expected 13:50; got 14:48
expected 13:53; got 14:51
expected 13:54; got 14:52
expected 13:57; got 14:55
expected 13:58; got 14:56
expected 14:01; got 14:59
expected 14:02; got 15:00
expected 14:05; got 15:03
expected 14:06; got 15:04
expected 14:09; got 15:07
expected 14:10; got 15:08
expected 14:13; got 15:11
expected 14:14; got 15:12
expected 14:18; got 15:16
expected 14:19; got 15:17
expected 14:22; got 15:20
expected 14:23; got 15:21
expected 14:26; got 15:24
expected 14:27; got 15:25
expected 14:30; got 15:28
expected 14:31; got 15:29
expected 14:34; got 15:32
expected 14:35; got 15:33
expected 14:38; got 15:36
expected 14:39; got 15:37
expected 14:42; got 15:40
expected 14:43; got 15:41
expected 14:46; got 15:44
expected 14:47; got 15:45
expected 14:50; got 15:48
expected 14:51; got 15:49
expected 14:54; got 15:52
expected 14:55; got 15:53
expected 14:58; got 15:56
expected 14:59; got 15:57
expected 15:03; got 16:01
expected 15:04; got 16:02
expected 15:07; got 16:05
expected 15:08; got 16:06
expected 15:11; got 16:09
expected 15:12; got 16:10
expected 15:15; got 16:13
expected 15:16; got 16:14
expected 15:19; got 16:17
expected 15:20; got 16:18
expected 15:23; got 16:21
expected 15:24; got 16:22
expected 15:27; got 16:25
expected 15:28; got 16:26
expected 15:31; got 16:29
expected 15:32; got 16:30
expected 15:35; got 16:33
expected 15:36; got 16:34
expected 15:39; got 16:37
expected 15:40; got 16:38
expected 15:43; got 16:41
expected 15:44; got 16:42
expected 15:48; got 16:46
expected 15:49; got 16:47
expected 15:52; got 16:50
expected 15:53; got 16:51
expected 15:56; got 16:54
expected 15:57; got 16:55
expected 16:00; got 16:58
expected 16:01; got 16:59
expected 16:04; got 17:02
expected 16:05; got 17:03
expected 16:08; got 17:06
expected 16:09; got 17:07
expected 16:12; got 17:10
expected 16:13; got 17:11
expected 16:16; got 17:14
expected 16:17; got 17:15
expected 16:20; got 17:18
expected 16:21; got 17:19
expected 16:24; got 17:22
expected 16:25; got 17:23
expected 16:28; got 17:26
expected 16:29; got 17:27
expected 16:33; got 17:31
expected 16:34; got 17:32
expected 16:37; got 17:35
expected 16:38; got 17:36
expected 16:41; got 17:39
expected 16:42; got 17:40
expected 16:45; got 17:43
expected 16:46; got 17:44
expected 16:49; got 17:47
expected 16:50; got 17:48
expected 16:53; got 17:51
expected 16:54; got 17:52
expected 16:57; got 17:55
expected 16:58; got 17:56
expected 17:01; got 17:59
expected 17:02; got 18:00
expected 17:05; got 18:03
expected 17:06; got 18:04
expected 17:09; got 18:07
expected 17:10; got 18:08
expected 17:13; got 18:11
expected 17:14; got 18:12
expected 17:18; got 18:16
expected 17:19; got 18:17
expected 17:22; got 18:20
expected 17:23; got 18:21
expected 17:26; got 18:24
expected 17:27; got 18:25
expected 17:30; got 18:28
expected 17:31; got 18:29
expected 17:34; got 18:32
expected 17:35; got 18:33
expected 17:38; got 18:36
expected 17:39; got 18:37
expected 17:42; got 18:40
expected 17:43; got 18:41
expected 17:46; got 18:44
expected 17:47; got 18:45
expected 17:50; got 18:48
expected 17:51; got 18:49
expected 17:54; got 18:52
expected 17:55; got 18:53
expected 17:58; got 18:56
expected 17:59; got 18:57
expected 18:03; got 19:01
expected 18:04; got 19:02
expected 18:07; got 19:05
expected 18:08; got 19:06
expected 18:11; got 19:09
expected 18:12; got 19:10
expected 18:15; got 19:13
expected 18:16; got 19:14
expected 18:19; got 19:17
expected 18:20; got 19:18
expected 18:23; got 19:21
expected 18:24; got 19:22
expected 18:27; got 19:25
expected 18:28; got 19:26
expected 18:31; got 19:29
expected 18:32; got 19:30
expected 18:35; got 19:33
expected 18:36; got 19:34
expected 18:39; got 19:37
expected 18:40; got 19:38
expected 18:43; got 19:41
expected 18:44; got 19:42
expected 18:48; got 19:46
expected 18:49; got 19:47
expected 18:52; got 19:50
expected 18:53; got 19:51
expected 18:56; got 19:54
expected 18:57; got 19:55
expected 19:00; got 19:58
expected 19:01; got 19:59
expected 19:04; got 20:02
expected 19:05; got 20:03
expected 19:08; got 20:06
expected 19:09; got 20:07
expected 19:12; got 20:10
expected 19:13; got 20:11
expected 19:16; got 20:14
expected 19:17; got 20:15
expected 19:20; got 20:18
expected 19:21; got 20:19
expected 19:24; got 20:22
expected 19:25; got 20:23
expected 19:28; got 20:26
expected 19:29; got 20:27
expected 19:33; got 20:31
expected 19:34; got 20:32
expected 19:37; got 20:35
expected 19:38; got 20:36
expected 19:41; got 20:39
expected 19:42; got 20:40
expected 19:45; got 20:43
expected 19:46; got 20:44
expected 19:49; got 20:47
expected 19:50; got 20:48
expected 19:53; got 20:51
expected 19:54; got 20:52
expected 19:57; got 20:55
expected 19:58; got 20:56
expected 20:01; got 20:59
expected 20:02; got 21:00
expected 20:05; got 21:03
expected 20:06; got 21:04
expected 20:09; got 21:07
expected 20:10; got 21:08
expected 20:13; got 21:11
expected 20:14; got 21:12
expected 20:18; got 21:16
expected 20:19; got 21:17
expected 20:22; got 21:20
expected 20:23; got 21:21
expected 20:26; got 21:24
expected 20:27; got 21:25
expected 20:30; got 21:28
expected 20:31; got 21:29
expected 20:34; got 21:32
expected 20:35; got 21:33
expected 20:38; got 21:36
expected 20:39; got 21:37
expected 20:42; got 21:40
expected 20:43; got 21:41
expected 20:46; got 21:44
expected 20:47; got 21:45
expected 20:50; got 21:48
expected 20:51; got 21:49
expected 20:54; got 21:52
expected 20:55; got 21:53
expected 20:58; got 21:56
expected 20:59; got 21:57
expected 21:03; got 22:01
expected 21:04; got 22:02
expected 21:07; got 22:05
expected 21:08; got 22:06
expected 21:11; got 22:09
expected 21:12; got 22:10
expected 21:15; got 22:13
expected 21:16; got 22:14
expected 21:19; got 22:17
expected 21:20; got 22:18
expected 21:23; got 22:21
expected 21:24; got 22:22
expected 21:27; got 22:25
expected 21:28; got 22:26
expected 21:31; got 22:29
expected 21:32; got 22:30
expected 21:35; got 22:33
expected 21:36; got 22:34
expected 21:39; got 22:37
expected 21:40; got 22:38
expected 21:43; got 22:41
expected 21:44; got 22:42
expected 21:48; got 22:46
expected 21:49; got 22:47
expected 21:52; got 22:50
expected 21:53; got 22:51
expected 21:56; got 22:54
expected 21:57; got 22:55
expected 22:00; got 22:58
expected 22:01; got 22:59
expected 22:04; got 23:02
expected 22:05; got 23:03
expected 22:08; got 23:06
expected 22:09; got 23:07
expected 22:12; got 23:10
expected 22:13; got 23:11
expected 22:16; got 23:14
expected 22:17; got 23:15
expected 22:20; got 23:18
expected 22:21; got 23:19
expected 22:24; got 23:22
expected 22:25; got 23:23
expected 22:28; got 23:26
expected 22:29; got 23:27
expected 22:33; got 23:31
expected 22:34; got 23:32
expected 22:37; got 23:35
expected 22:38; got 23:36
expected 22:41; got 23:39
expected 22:42; got 23:40
expected 22:45; got 23:43
expected 22:46; got 23:44
expected 22:49; got 23:47
expected 22:50; got 23:48
expected 22:53; got 23:51
expected 22:54; got 23:52
expected 22:57; got 23:55
expected 22:58; got 23:56
expected 23:01; got 23:59
expected 23:02; got 00:00
expected 23:05; got 00:03
expected 23:06; got 00:04
expected 23:09; got 00:07
expected 23:10; got 00:08
expected 23:13; got 00:11
expected 23:14; got 00:12
expected 23:18; got 00:16
expected 23:19; got 00:17
expected 23:22; got 00:20
expected 23:23; got 00:21
expected 23:26; got 00:24
expected 23:27; got 00:25
expected 23:30; got 00:28
expected 23:31; got 00:29
expected 23:34; got 00:32
expected 23:35; got 00:33
expected 23:38; got 00:36
expected 23:39; got 00:37
expected 23:42; got 00:40
expected 23:43; got 00:41
expected 23:46; got 00:44
expected 23:47; got 00:45
expected 23:50; got 00:48
expected 23:51; got 00:49
expected 23:54; got 00:52
expected 23:55; got 00:53
expected 23:58; got 00:56
expected 23:59; got 00:57
```

It's a very odd behavior that is happening right now and I think it's incorrect. You can see this happening with 13:45 time for instance.

Thanks!

### PR DESCRIPTION
**Pull request by santsai**
@tealeg @frezadev
incorrect parsed date fix #229 #241 
the original version has problems when calculating seconds value & has rounding issues
this fix would calculation the seconds value correctly and round the it nearest 1us.

### CODE REVIEW

**Comment by tealeg** [comment]
@santsai great, thanks for you work!

**Comment by frezadev** [comment]
@santsai @tealeg thanks all

**Comment by tealeg** [comment]
@frezadev I did almost nothing, but hey, I'll take praise for pushing the buttons too ;-)

**Comment by santsai** [comment]
lol @tealeg it would be great if you take a look and push some buttons at #233 :)

**Comment by tealeg** [comment]
@santsai your wish is my command! ;-)

**Comment by frezadev** [comment]
@tealeg you are the boss :D

**Pull request merged**
